const Sdata = [
  {
    id: 1,
    title: "Travaux de construction et de finition",
    image: "/images/t6.jpg",
    desc: "Les travaux de construction et de finition proposés par Cherradi Solutions couvrent un large éventail de services, allant de la construction de nouveaux bâtiments à la rénovation et à l'embellissement des structures existantes. Notre équipe qualifiée et expérimentée s'engage à fournir des résultats de qualité, quel que soit le projet. Nous offrons des services de construction résidentielle, commerciale et industrielle, ainsi que des travaux de finition intérieure et extérieure, tels que la pose de revêtements de sol, la peinture, le plâtrage et bien plus encore. Que vous ayez besoin de créer un nouvel espace ou de donner une nouvelle vie à un bâtiment existant, Cherradi Solutions est là pour répondre à vos besoins en matière de construction et de finition, avec professionnalisme et excellence.",
    sidepara: "N'hésitez pas à nous contacter dès maintenant par téléphone. Notre équipe dévouée est là pour répondre à toutes vos interrogations et vous fournir les informations dont vous avez besoin pour prendre des décisions éclairées. Appelez-nous dès aujourd'hui et laissez-nous vous aider à trouver la solution parfaite pour vos besoins. Nous sommes impatients de discuter avec vous !",
    // paraImage_one: "images/t6.jpg",
    // paraImage_two: "images/t6-1.jpg",
  },
  {
    id: 2,
    title: "Travaux de plomberie et d'électricité",
    image: "images/t7.jpg",
    desc: "Les services de plomberie et d'électricité offerts par Cherradi Solutions sont conçus pour répondre à tous vos besoins en matière d'installations, de réparations et de maintenance. Notre équipe qualifiée de plombiers et d'électriciens est là pour vous aider à résoudre tout problème, des fuites de tuyaux aux pannes électriques, en passant par l'installation de nouveaux équipements. Que ce soit pour votre domicile, votre entreprise ou votre site industriel, vous pouvez compter sur notre expertise pour des solutions fiables et durables. Nous sommes déterminés à assurer votre sécurité et votre confort en fournissant un travail de qualité et un service à la clientèle exceptionnel. Pour tous vos besoins en plomberie et en électricité, faites confiance à Cherradi Solutions.",
    sidepara: "N'hésitez pas à nous contacter dès maintenant par téléphone. Notre équipe dévouée est là pour répondre à toutes vos interrogations et vous fournir les informations dont vous avez besoin pour prendre des décisions éclairées. Appelez-nous dès aujourd'hui et laissez-nous vous aider à trouver la solution parfaite pour vos besoins. Nous sommes impatients de discuter avec vous !",
  },
  {
    id: 3,
    title: "Services de jardinage et de nettoyage",
    image: "/images/t8.jpg",
    desc: "Cherradi Solutions propose une gamme complète de services de jardinage et de nettoyage pour vous aider à maintenir et à embellir vos espaces extérieurs et intérieurs. Notre équipe de professionnels qualifiés en jardinage est là pour prendre soin de votre jardin, de la tonte de la pelouse à la taille des arbustes et à l'entretien des parterres de fleurs. Nous travaillons avec vous pour créer un environnement extérieur magnifique et accueillant qui correspond à vos besoins et à vos préférences.",
    desc2:"En ce qui concerne le nettoyage, notre équipe expérimentée est équipée pour répondre à tous vos besoins de nettoyage, que ce soit pour votre domicile, votre bureau ou votre site commercial. Nous offrons des services de nettoyage réguliers ou ponctuels, y compris le nettoyage des sols, des fenêtres, des tapis, des meubles, et bien plus encore. Nous nous engageons à fournir des résultats impeccables et à assurer votre satisfaction à chaque visite.",
    desc3:"Qu'il s'agisse de transformer votre jardin en un havre de paix verdoyant ou de maintenir la propreté et la fraîcheur de vos espaces intérieurs, Cherradi Solutions est votre partenaire de confiance pour des services de jardinage et de nettoyage de qualité supérieure.",
    sidepara: "N'hésitez pas à nous contacter dès maintenant par téléphone. Notre équipe dévouée est là pour répondre à toutes vos interrogations et vous fournir les informations dont vous avez besoin pour prendre des décisions éclairées. Appelez-nous dès aujourd'hui et laissez-nous vous aider à trouver la solution parfaite pour vos besoins. Nous sommes impatients de discuter avec vous !",
  },
  {
    id: 4,
    title: "Construction métallique",
    image: "/images/t9.jpg",
    desc: " Cherradi Solutions offre des services de construction métallique de haute qualité pour répondre à vos besoins spécifiques en matière de structures métalliques. Que vous envisagiez de construire un nouvel entrepôt, un bâtiment commercial, industriel ou agricole, ou même des structures spécifiques telles que des hangars ou des passerelles, notre équipe expérimentée est là pour vous accompagner à chaque étape du processus.",
    desc2:"Nous combinons notre expertise technique avec des matériaux de haute qualité pour concevoir et construire des structures métalliques robustes, durables et esthétiquement agréables. Notre approche personnalisée nous permet de travailler en étroite collaboration avec vous pour comprendre vos besoins et vos objectifs, afin de fournir des solutions sur mesure qui dépassent vos attentes.",
    desc3:"Que ce soit pour des projets de petite ou de grande envergure, vous pouvez compter sur Cherradi Solutions pour fournir un travail de qualité, respectant les délais et le budget, dans le domaine de la construction métallique. Nous sommes déterminés à vous fournir des solutions de construction métallique innovantes et fiables qui répondent à vos besoins spécifiques et contribuent à la réussite de votre projet.",
    sidepara: "N'hésitez pas à nous contacter dès maintenant par téléphone. Notre équipe dévouée est là pour répondre à toutes vos interrogations et vous fournir les informations dont vous avez besoin pour prendre des décisions éclairées. Appelez-nous dès aujourd'hui et laissez-nous vous aider à trouver la solution parfaite pour vos besoins. Nous sommes impatients de discuter avec vous !",
  },
  {
    id: 5,
    title: "Vente et réparation de matériel informatique",
    image: "/images/t10.jpg",
    desc: "Cherradi Solutions propose une gamme complète de services pour répondre à vos besoins en matière de matériel informatique. Que vous recherchiez des équipements neufs ou que vous ayez besoin de réparations sur du matériel existant, notre équipe compétente est là pour vous aider.",
    desc2:"En tant que fournisseur de confiance, nous vous proposons une sélection soigneusement choisie de matériel informatique de qualité, comprenant des ordinateurs de bureau, des ordinateurs portables, des périphériques, des imprimantes et bien plus encore. Notre objectif est de vous fournir des solutions informatiques fiables et performantes pour répondre à vos besoins professionnels ou personnels.",
    desc3:"En plus de la vente de matériel informatique, notre équipe de techniciens qualifiés est disponible pour diagnostiquer et réparer tout problème matériel que vous pourriez rencontrer. Que ce soit pour résoudre des problèmes de matériel, effectuer des mises à niveau ou même récupérer des données, nous sommes là pour vous offrir un service rapide et efficace pour vous remettre en marche le plus rapidement possible.",
    desc4:"Faites confiance à Cherradi Solutions pour tous vos besoins en matériel informatique, que ce soit pour l'achat de nouveaux équipements ou pour des réparations professionnelles et fiables. Nous nous engageons à fournir des solutions informatiques de qualité et un service client exceptionnel pour vous aider à rester opérationnel et productif.",
    sidepara: "N'hésitez pas à nous contacter dès maintenant par téléphone. Notre équipe dévouée est là pour répondre à toutes vos interrogations et vous fournir les informations dont vous avez besoin pour prendre des décisions éclairées. Appelez-nous dès aujourd'hui et laissez-nous vous aider à trouver la solution parfaite pour vos besoins. Nous sommes impatients de discuter avec vous !",
  },
  {
    id: 6,
    title: "Fournitures et accessoires informatiques,et électroniques",
    image: "/images/t11.jpg",
    desc: "Cherradi Solutions est votre destination privilégiée pour toutes vos fournitures et accessoires informatiques et électroniques. Nous proposons une large gamme de produits de qualité pour répondre à vos besoins professionnels et personnels en matière de technologie.",
    desc2:"Que vous ayez besoin de câbles, de périphériques, de cartouches d'encre, de sacs pour ordinateurs portables ou d'autres accessoires, nous avons tout ce dont vous avez besoin pour compléter votre configuration informatique. Notre sélection comprend également une variété de produits électroniques, tels que des casques audio, des souris sans fil, des batteries de secours et bien plus encore.",
    desc3:"Nous nous engageons à fournir à nos clients des produits de qualité des meilleures marques, afin de garantir des performances fiables et durables. Notre équipe compétente est là pour vous conseiller et vous aider à trouver les produits les mieux adaptés à vos besoins spécifiques, tout en respectant votre budget.",
    desc4:"Faites confiance à Cherradi Solutions pour tous vos besoins en fournitures et accessoires informatiques et électroniques. Nous nous engageons à vous offrir une expérience d'achat agréable et un service client exceptionnel à chaque étape du processus.",
    sidepara: "N'hésitez pas à nous contacter dès maintenant par téléphone. Notre équipe dévouée est là pour répondre à toutes vos interrogations et vous fournir les informations dont vous avez besoin pour prendre des décisions éclairées. Appelez-nous dès aujourd'hui et laissez-nous vous aider à trouver la solution parfaite pour vos besoins. Nous sommes impatients de discuter avec vous !",
  },
]

export default Sdata
